# When modifying this file, please validate using
# curl -X POST --data-binary @codecov.yml https://codecov.io/validate

# See also https://docs.codecov.com/docs/codecov-yaml#repository-yaml and
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  status:
    # https://docs.codecov.com/docs#tips-and-tricks
    project:
      default:
        informational: true # Fail the pipeline?
    patch:
      default:
        informational: true # Fail the pipeline?
ignore:
  # https://docs.codecov.com/docs/codecovyml-reference#ignore
  - "build.rs"
